### ISSUE TITLE
Import Resolve Failure

### ISSUE THREAD

**Issue by ludoZici** [Stability-AI/StableStudio#27]
Morning all - 

After installation it worked, this is what I ran into the next day...suggestions?  Thanks in advance!

10:04:22 AM [vite] Internal server error: Failed to resolve import "~/GlobalVariables" from "src\index.tsx". Does the file exist?
➤ YN0000: [@stability/stablestudio-ui]:   Plugin: vite:import-analysis
➤ YN0000: [@stability/stablestudio-ui]:   File: C:/Windows/System32/StableStudio/packages/stablestudio-ui/src/index.tsx:3:7
➤ YN0000: [@stability/stablestudio-ui]:   1  |  import { jsxDEV } from "@emotion/react/jsx-dev-runtime";
➤ YN0000: [@stability/stablestudio-ui]:   2  |  import ReactDOM from "react-dom/client";
➤ YN0000: [@stability/stablestudio-ui]:   3  |  import "~/GlobalVariables";
➤ YN0000: [@stability/stablestudio-ui]:      |          ^
➤ YN0000: [@stability/stablestudio-ui]:   4  |  import { App } from "~/App";
➤ YN0000: [@stability/stablestudio-ui]:   5  |  const main = async () => {
➤ YN0000: [@stability/stablestudio-ui]:       at formatError (file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42597:46)
➤ YN0000: [@stability/stablestudio-ui]:       at TransformContext.error (file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42593:19)
➤ YN0000: [@stability/stablestudio-ui]:       at normalizeUrl (file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40509:33)
➤ YN0000: [@stability/stablestudio-ui]:       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
➤ YN0000: [@stability/stablestudio-ui]:       at async file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40652:47
➤ YN0000: [@stability/stablestudio-ui]:       at async Promise.all (index 2)
➤ YN0000: [@stability/stablestudio-ui]:       at async TransformContext.transform (file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40578:13)
➤ YN0000: [@stability/stablestudio-ui]:       at async Object.transform (file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42871:30)
➤ YN0000: [@stability/stablestudio-ui]:       at async loadAndTransform (file:///C:/WINDOWS/system32/StableStudio/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:53335:29)

**Comment by cruhl** [comment]
Hello! I can't replicate this, have any more information on how I can get this to happen on my end?

**Comment by ludoZici** [comment]
Hello! I wish I could provide more.  I installed the day before per the documentation, windows 10, all patches and updates, functioned perfectly.  The next morning I fired it up and received the aforementioned failure.  Happy to provide whatever can assist, let me know.

**Comment by mcarlssen** [comment]
I reproduced this error on a clean install (Win10 `22H2`, Node `18.16.0`) by executing as admin.

**Comment by ludoZici** [comment]
Thanks mikethorn, that was it!
