### ISSUE TITLE
StableStudio on Google Collab

### ISSUE THREAD

**Issue by cruhl** [Stability-AI/StableStudio#30]
### Discussed in https://github.com/Stability-AI/StableStudio/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **AbdirayimovS** May 19, 2023</sup>
Hi there, 

I wonder if there is a Google collab notebook to easily install and run StableStudio. 

1. I created a new Google Collab notebook!
2. Installed nodejs
    `!sudo apt install nodejs npm
     !npm install`
3. Installed yarn
    `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt update && sudo apt install yarn
     yarn`
4.  Copied the repo and run the folowing code:
     `git clone https://github.com/Stability-AI/StableStudio.git
      cd StableStudio
      yarn
      yarn dev`

# The **error** I am getting:
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /content/StableStudio/.yarn/releases/yarn-3.3.0.cjs:423:2587
    at Object.<anonymous> (/content/StableStudio/.yarn/releases/yarn-3.3.0.cjs:740:8833)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)`
</div>

**Comment by cruhl** [comment]
Getting this working in Google Collab would be pretty neat

**Comment by camenduru** [comment]
https://github.com/camenduru/StableStudio-colab

**Comment by felipeavilis** [comment]
Same error here... any ideas? Im using a VM in Azure.

> ### Discussed in #26
> Originally posted by **AbdirayimovS** May 19, 2023 Hi there,
> 
> I wonder if there is a Google collab notebook to easily install and run StableStudio.
> 
> 1. I created a new Google Collab notebook!
> 2. Installed nodejs
>    `!sudo apt install nodejs npm !npm install`
> 3. Installed yarn
>    `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list sudo apt update && sudo apt install yarn yarn`
> 4. Copied the repo and run the folowing code:
>    `git clone https://github.com/Stability-AI/StableStudio.git cd StableStudio yarn yarn dev`
> 
> # The **error** I am getting:
> `internal/modules/cjs/loader.js:638 throw err; ^
> 
> Error: Cannot find module 'worker_threads' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at /content/StableStudio/.yarn/releases/yarn-3.3.0.cjs:423:2587 at Object. (/content/StableStudio/.yarn/releases/yarn-3.3.0.cjs:740:8833) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12)`

**Comment by kopyl** [comment]
@felipeavilis same on Azure VM... Seems like it can't even work on bare metal.
Open source as it is – always does not work.

**Comment by kopyl** [comment]
@felipeavilis fixed it by updating node version to the latest:

From the [official nodejs website](https://nodejs.org/en/download/package-manager):
```
# installs fnm (Fast Node Manager)
curl -fsSL https://fnm.vercel.app/install | bash
# activate fnm
source ~/.bashrc
# download and install Node.js
fnm use --install-if-missing 23
# verifies the right Node.js version is in the environment
node -v # should print `v23.3.0`
# verifies the right npm version is in the environment
npm -v # should print `10.9.0`
```
