### ISSUE TITLE
I tried to install StableStudio, but it fails on step 3. 

### ISSUE THREAD

**Issue by crantisz** [Stability-AI/StableStudio#84]
**Describe the bug**
I tried to install StableStudio, but it fails on step 3. 

**To Reproduce**
1. git clone https://github.com/Stability-AI/StableStudio.git
2. cd StableStudio
3. yarn
```
michael@michael-X570-UD:~/StableStudio$ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @stability/stablestudio-plugin-example@workspace:packages/stablestudio-plugin-example doesn't provide @types/node (pe4c4e), requested by ts-node
➤ YN0002: │ @stability/stablestudio-plugin-webgpu@workspace:packages/stablestudio-plugin-webgpu doesn't provide @types/node (p1e18d), requested by ts-node
➤ YN0002: │ @stability/stablestudio-plugin-webui@workspace:packages/stablestudio-plugin-webui doesn't provide @types/node (p09690), requested by ts-node
➤ YN0002: │ @stability/stablestudio-plugin@workspace:packages/stablestudio-plugin doesn't provide @types/node (pb7ed9), requested by ts-node
➤ YN0002: │ notistack@npm:3.0.1 [47cbf] doesn't provide csstype (p2d22e), requested by goober
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 283ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 339ms
➤ YN0000: ┌ Link step
➤ YN0007: │ root-workspace-0b6124@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ root-workspace-0b6124@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-a188f1f5/build.log)
➤ YN0000: └ Completed in 29s 759ms
➤ YN0000: Failed with errors in 30s 526ms
michael@michael-X570-UD:~/StableStudio$ cat /tmp/xfs-a188f1f5/build.log
# This file contains the result of Yarn building a package (root-workspace-0b6124@workspace:.)
# Script name: postinstall

husky - Git hooks installed
➤ YN0000: [@stability/stablestudio-plugin]: Process started
➤ YN0000: [@stability/stablestudio-plugin]: Process exited (exit code 0), completed in 3s 360ms

➤ YN0000: [@stability/stablestudio-plugin-example]: Process started
➤ YN0000: [@stability/stablestudio-plugin-example]: Process exited (exit code 0), completed in 3s 365ms

➤ YN0000: [@stability/stablestudio-plugin-stability]: Process started
➤ YN0000: [@stability/stablestudio-plugin-stability]: Process exited (exit code 0), completed in 5s 526ms

➤ YN0000: [@stability/stablestudio-plugin-webgpu]: Process started
➤ YN0000: [@stability/stablestudio-plugin-webgpu]: Process exited (exit code 0), completed in 3s 441ms

➤ YN0000: [@stability/stablestudio-plugin-webui]: Process started
➤ YN0000: [@stability/stablestudio-plugin-webui]: Process exited (exit code 0), completed in 3s 555ms

➤ YN0000: [@stability/stablestudio-ui]: Process started
➤ YN0000: [@stability/stablestudio-ui]: file:///home/michael/StableStudio/node_modules/vite/bin/vite.js:7
➤ YN0000: [@stability/stablestudio-ui]:     await import('source-map-support').then((r) => r.default.install())
➤ YN0000: [@stability/stablestudio-ui]:     ^^^^^
➤ YN0000: [@stability/stablestudio-ui]: 
➤ YN0000: [@stability/stablestudio-ui]: SyntaxError: Unexpected reserved word
➤ YN0000: [@stability/stablestudio-ui]:     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
➤ YN0000: [@stability/stablestudio-ui]:     at async link (internal/modules/esm/module_job.js:42:21)
➤ YN0000: [@stability/stablestudio-ui]: Process exited (exit code 1), completed in 8s 815ms
➤ YN0000: Done in 28s 67ms
michael@michael-X570-UD:~/StableStudio$ yarn --version
3.3.0       
michael@michael-X570-UD:~/StableStudio$ nodejs --version
v12.22.9
```

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04

**Comment by kaloyan-raev** [comment]
I hit the same issue and found that Ubuntu 22.04 has an outdated NodeJS version. Upgrading NodeJS to a more recent version solves the problem.

**Comment by vaibhavb02** [comment]
Update the node.js to latest version.

**Comment by DawnAve** [comment]
My "node -v" gives me v21.6.0, and I am still having the problem. btw, are node and nodejs the same thing?

**Comment by lalitkpal** [comment]
i have update to latest nodejs v21.6.1, still getting the same error:
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @stability/stablestudio-plugin-example@workspace:packages/stablestudio-plugin-example doesn't provide @types/node (pe4c4e), requested by ts-node
➤ YN0002: │ @stability/stablestudio-plugin-webgpu@workspace:packages/stablestudio-plugin-webgpu doesn't provide @types/node (p1e18d), requested by ts-node
➤ YN0002: │ @stability/stablestudio-plugin-webui@workspace:packages/stablestudio-plugin-webui doesn't provide @types/node (p09690), requested by ts-node
➤ YN0002: │ @stability/stablestudio-plugin@workspace:packages/stablestudio-plugin doesn't provide @types/node (pb7ed9), requested by ts-node
➤ YN0002: │ notistack@npm:3.0.1 [47cbf] doesn't provide csstype (p2d22e), requested by goober
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 243ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 383ms
➤ YN0000: ┌ Link step
➤ YN0007: │ root-workspace-0b6124@workspace:. must be built because it never has been before or the last one failed
➤ YN0009: │ root-workspace-0b6124@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-53e76404/build.log)
➤ YN0000: └ Completed in 0s 395ms
➤ YN0000: Failed with errors in 1s 81ms
