### ISSUE TITLE
Images start to generate but quickly disappear

### ISSUE THREAD

**Issue by Epigeos-com** [Stability-AI/StableStudio#90]
**Describe the bug**
Images start to generate but quickly disappear

**To Reproduce**
I don't really know, it sometimes works and sometimes doesn't (but usually doesn't), couldn't figure out when

**Expected behavior**
The images start to generate but quickly disappear

**Screenshots**
https://github.com/Stability-AI/StableStudio/assets/133534868/0d322eb4-ac92-4db3-8ab4-524b233fd4da

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Google Chrome, Microsoft
 - Version: [e.g. 22]

**Additional context**

**Comment by oneakroller** [comment]
**With debug I got this. "TypeError: Cannot read properties of undefined (reading 'match')" last line: Process exited **

➤ YN0000: [@stability/stablestudio-plugin]: Process started
➤ YN0000: [@stability/stablestudio-plugin-example]: Process started
➤ YN0000: [@stability/stablestudio-plugin-stability]: Process started
➤ YN0000: [@stability/stablestudio-plugin-webgpu]: Process started
➤ YN0000: [@stability/stablestudio-plugin-webui]: Process started
➤ YN0000: [@stability/stablestudio-ui]: Process started
➤ YN0000: [@stability/stablestudio-plugin]: /home/oneak/StableStudio/node_modules/nodemon/lib/cli/parse.js:220
➤ YN0000: [@stability/stablestudio-plugin]:   if (value.match(/^\d*ms$/)) {
➤ YN0000: [@stability/stablestudio-plugin]:             ^
➤ YN0000: [@stability/stablestudio-plugin]:
➤ YN0000: [@stability/stablestudio-plugin]: TypeError: Cannot read properties of undefined (reading 'match')
➤ YN0000: [@stability/stablestudio-plugin]:     at parseDelay (/home/oneak/StableStudio/node_modules/nodemon/lib/cli/parse.js:220:13)
➤ YN0000: [@stability/stablestudio-plugin]:     at nodemonOption (/home/oneak/StableStudio/node_modules/nodemon/lib/cli/parse.js:168:21)
➤ YN0000: [@stability/stablestudio-plugin]:     at parse (/home/oneak/StableStudio/node_modules/nodemon/lib/cli/parse.js:81:11)
➤ YN0000: [@stability/stablestudio-plugin]:     at Object.parse (/home/oneak/StableStudio/node_modules/nodemon/lib/cli/index.js:47:12)
➤ YN0000: [@stability/stablestudio-plugin]:     at Object.<anonymous> (/home/oneak/StableStudio/node_modules/nodemon/bin/nodemon.js:5:21)
➤ YN0000: [@stability/stablestudio-plugin]:     at Module._compile (node:internal/modules/cjs/loader:1099:14)
➤ YN0000: [@stability/stablestudio-plugin]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
➤ YN0000: [@stability/stablestudio-plugin]:     at Module.load (node:internal/modules/cjs/loader:975:32)
➤ YN0000: [@stability/stablestudio-plugin]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
➤ YN0000: [@stability/stablestudio-plugin]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
➤ YN0000: [@stability/stablestudio-plugin]:
➤ YN0000: [@stability/stablestudio-plugin]: Node.js v17.9.1
**➤ YN0000: [@stability/stablestudio-plugin]: Process exited (exit code 1), completed in 0s 591ms**

**Comment by jtydhr88** [comment]
@PSp-studios could you provide more context, for example, which backend you are using? local sd-webui or conneting Stability api? And a browser error log (F12) would be more helpful!

**Comment by broadysm** [comment]
I also had the same experience.

I think it's related to the original DreamStudio's API Key.

StableStudio does not charge a fee to generate pictures, but it seems that if you use an API key that is reached to the DreamStudio's picture generation limit, StableStudio will not be able to create photos either. No more picture limit API key is also recognized in StableStudio too.

The situation witch occurs in the SableStudio is almost the same in DreamStudio that does not generate pictures. Try to generate picktures but disappears.

It seems that the billing routines are not completely ruled out in StableStudio. I think the first check of API state routine is included in StableStudio.

**Comment by h-mortazavifar** [comment]
Same issue here. How comes it uses DreamStudio credits?!

**Comment by cognivator** [comment]
+1

My (brand new, today) DreamStudio account has 25 credits avail, but every prompt - including the examples - results in, "Sorry, something went wrong on our end..." errors.

StableStudio - locally cloned, installed, and API key from DS account - also doesn't generate images, but with no error message.

I'm guessing the DS failure is what is preventing SS to succeed, yes?

How do we fix this?
